### ISSUE TITLE
After delete an entry, if view all item with function '1' could cause infinite loop

### ISSUE THREAD

**Issue by Tbthanh** [buihuy1203/student_data#1]
![image](https://github.com/buihuy1203/Student-Data-Project/assets/90943148/b266c935-bddf-4624-b689-6b08f01f797e)

https://github.com/buihuy1203/Student-Data-Project/assets/90943148/7e16e986-642f-4f85-a232-818002f97685

Here are the pics and vid of the problem.

**Comment by buihuy1203** [comment]
Just finish fixing it, you can download the new file right now
