### ISSUE TITLE
Cannot delete two entry continuously

### ISSUE THREAD

**Issue by Tbthanh** [buihuy1203/student_data#2]
https://github.com/buihuy1203/Student-Data-Project/assets/90943148/11a9d68a-2eb6-4599-83b5-74fd17c09614

![image](https://github.com/buihuy1203/Student-Data-Project/assets/90943148/005cd6be-8fc1-4073-8f49-e5b2c2db3dcd)

When delete one after another, the programe froze.

**Comment by buihuy1203** [comment]
I just updated with a new code file, you can try it again
